name: Deploy
on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch (or specify another branch)
  pull_request:
    branches:
      - main  # Trigger workflow on PR to the main branch (or specify another branch)
  workflow_dispatch:  # Manual trigger from GitHub UI
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate HTML Documentation
        run: |
          python docgen.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
